### ISSUE TITLE
synthetic/derived attributes

### ISSUE THREAD

**Issue by bantic** [miragejs/ember-cli-mirage#1325]
This was discussed [in slack](https://embercommunity.slack.com/archives/C0TG21RPW/p1528209958000657), and it was suggested to add a tracking issue here to keep track of it.

Sometimes an API will send attributes that are composed of others. An example would be an API that doesn't conform to JSON API and sends a `parent_id` attribute instead of putting that linkage in the `relationships` hash.

Right now Mirage has the `attrs` property that can be set on serializes to whitelist the attributes that will be included in serialization, and one can also override the `serialize` method to alter the json payload, but there isn't an easy way to identify `attrs` that don't map directly to properties on the Mirage model instance.

One suggestion is to add a `syntheticAttrs` namespace to the serializer:
```javascript
// app/models/comment.js
export default DS.Model.extend({
  post: DS.belongsTo('post')
})

// mirage/serializers/comment.js
export default JSONApiSerializer.extend({
  syntheticAttrs: {
    postId(comment) {
      return comment.postId;
    }
  }
})
```

Other suggested namespaces were `derivedAttributes`, `syntheticAttributes`, `derivedAttrs`.

**Comment by samselikoff** [comment]
Closing this as we have a discuss issue for this feature idea now: https://github.com/miragejs/discuss/issues/6
