### ISSUE TITLE
Polymorphic relationship not working as expected

### ISSUE THREAD

**Issue by npendery** [miragejs/ember-cli-mirage#1341]
Mirage version: `0.4.7`

I am trying to get this polymorphic relation to work but getting a error of: `model.hasInverseFor is not a function` when saving the `friendship-request` record with a `requestee` and `requester`. I essentially would like to have both my `user-types` to be able to be either a `requester` or `requestee`. I _think_ I am just messing up the models but cant figure it out. These are the models:

```js
// models/friendship-request.js
import { Model, belongsTo } from 'ember-cli-mirage'

export default Model.extend({
  requestee: belongsTo({ polymorphic: true }),
  requester: belongsTo({ polymorphic: true })
})
```

```js
// models/actor.js
import { Model, hasMany } from 'ember-cli-mirage'

export default Model.extend({
  friendshipRequests: hasMany()
  // I have tried things such as:
  // friendshipRequested: hasMany({ polymorphic: 'requestee', inverse: 'friendship-request' }),
  // friendshipRequesting: hasMany({ polymorphic: 'requester', inverse: 'friendship-request' })
})
```

```js
// models/agent.js
import { Model, hasMany } from 'ember-cli-mirage'

export default Model.extend({
  friendshipRequests: hasMany()
})
```

**Comment by samselikoff** [comment]
Here's a twiddle showing the model setup & creating some data from mirage's `scenario/default.js`: 

https://ember-twiddle.com/44cdfb281a217507d6907e93a4211996?openFiles=mirage.scenarios.default.js%2C

It seems to be working. What are you doing that's leading to the error?

**Comment by samselikoff** [comment]
Closing as stale – let me know if you still need help!
