### ISSUE TITLE
Ability to share/import multiple Mirage configs

### ISSUE THREAD

**Issue by samselikoff** [miragejs/ember-cli-mirage#1413]
![image](https://user-images.githubusercontent.com/2922250/48871109-4fe1ea00-edb1-11e8-8505-a5bb6bf0bc24.png)

---

6 upvotes from Canny

**Comment by samselikoff** [comment]
Today, you can call `server.config(options)` as many times as you want, thereby "augmenting" your server with additional config objects.

We also have another discussion issue focused on sharing Mirage configs across ember apps/addons: https://github.com/miragejs/discuss/issues/7

So for now I'll close this one!

**Comment by jonchay** [comment]
@samselikoff could you explain a bit more of how to call `server.config(options)` multiple times? I'm trying to setup multiple config with different namespaces under `mirage/config.js` but there are no documentation to describe how.

Happy to submit a PR for updating docs if we could find a solution!

**Comment by samselikoff** [comment]
Sure, just that you can do

```
let server = new Server({
  models: {
    user: Model
  }
})

server.config({
  models: {
    message: Model
  }
})
```

Def should be documented! `config` method on `Server` class: https://miragejs.com/api/classes/server/

**Comment by samselikoff** [comment]
Sorry, just realized this is ember-cli-mirage repo.

So you'd need to get a hold of the Mirage server instance so you can call `.config` like ^ above.

I would try to do it by doing `this.config()` in the function in `mirage/config.js` (since `this` is the server instance).
