### ISSUE TITLE
Document ability to use a predicate in the where filter

### ISSUE THREAD

**Issue by samselikoff** [miragejs/ember-cli-mirage#1426]
![image](https://user-images.githubusercontent.com/2922250/48871516-0f836b80-edb3-11e8-9a12-d71d254393b5.png)

---

2 upvotes from Canny

**Comment by Garibaldy** [comment]
I think we **must write** some **tests** to address this with a solution

**Comment by nselikoff** [comment]
I believe this is already possible, right @samselikoff? Per https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/db-collection.js#L399, a function can be passed to `DbCollection::where` that gets passed through to `_findRecordsWhere`.

**Comment by samselikoff** [comment]
@nselikoff believe he's talking about the ORM version (in this case on `Schema`) rather than the Db version

https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/orm/schema.js#L309

**Comment by samselikoff** [comment]
@nselikoff ah but you're saying it already works because ORM/collection just delegates to DbCollection.

We should update the docs

**Comment by samselikoff** [comment]
https://miragejs.com/api/classes/schema#where documents the function version of `where`
