### ISSUE TITLE
Trait composition

### ISSUE THREAD

**Issue by samselikoff** [miragejs/ember-cli-mirage#1429]
![image](https://user-images.githubusercontent.com/2922250/48871579-51141680-edb3-11e8-8538-f490122baf0f.png)

**Comment by Oreoz** [comment]
@samselikoff Opened a PR that attempts to add this feature. Happy to discuss. :)

**Comment by samselikoff** [comment]
Latest issue: https://github.com/miragejs/discuss/issues/24
