### ISSUE TITLE
Error with Embroider

### ISSUE THREAD

**Issue by villander** [miragejs/ember-cli-mirage#1594]
I'm using ember-cli-mirage 0.4.15 with ember-cli 3.8.1 + Embroider 0.3.4

I have this error on my browser when visited `http://localhost:4200`

```
![image](https://user-images.githubusercontent.com/10222774/56461418-18d82a80-6389-11e9-9fa0-f72fc74daacb.png)
```

https://github.com/embroider-build/embroider/issues/114#issuecomment-478310361

**Comment by samselikoff** [comment]
Thanks! Any chance you could upload a simplified reproduction?

**Comment by samselikoff** [comment]
Closing as stale but please let me know if you're still having any trouble!
