### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by AleksandrBorovkov** [miragejs/ember-cli-mirage#1610]
I've got error in console after installation of ember-cli-mirage package 

![image](https://user-images.githubusercontent.com/22237897/57306634-db470180-70eb-11e9-9d03-5aa5cf19cd07.png)

![image](https://user-images.githubusercontent.com/22237897/57306670-e8fc8700-70eb-11e9-8c86-2756bec3cd64.png)!

**Comment by AleksandrBorovkov** [comment]
Maybe similar to https://github.com/samselikoff/ember-cli-mirage/issues/939. I also use ember-ajax to perform specific requests

**Comment by samselikoff** [comment]
Sorry you're running into trouble!

Could you try to create a simplified reproduction?
Also, `country_id` smells a little off here... Mirage usually uses camelCase internally everywhere. What's `reopen-model.js` doing?

The error also looks like it's coming from Ember Data rather than Mirage.

**Comment by samselikoff** [comment]
Closing as stale, please let me know if you're still running into any issues!
