### ISSUE TITLE
Unable to get Mirage to intercept calls

### ISSUE THREAD

**Issue by mdbiscan** [miragejs/ember-cli-mirage#1697]
**Ember CLI: v3.11
Mirage: v1.1.0**

I'm setting up an app using mirage, following these steps found in the installation guide and the overview:

1.`ember install ember-cli-mirage`
2. Add to config.js:
```javascript
export default function() {
  this.get('/routines');
}
```
3. Create an ember and an ember-mirage model for `routine`

When making a call for all routines, in the ember Route, the model hook is used:

```javascript
export default Route.extend({
  model() {
    return this.store.findAll('routine');
  },
});
```

When I go to the route in my app, a call is made to `get` routines at `/routines`, which the mirage config is set up to listen to. However, I get this 404 error:

```javascript
Error while processing route: scenarios.index Ember Data Request GET /routines returned a 404
```

Instead of mirage intercepting `/routines`, the app is hitting `http://localhost:4200/routines`, which doesn't exist for obvious reasons. I've tried this a few times, starting over from scratch, but I continue to have this problem. I've confirmed that the mirage config is loading and I haven't made any additional setup other than what is recommended.

**Comment by samselikoff** [comment]
Looking into it. Do you happen to have the repo handy & could upload it?

**Comment by mdbiscan** [comment]
I don't have a repo I could share, its a private project that I'm not the owner of. 

`/config/environment.js`
```javascript
'use strict';

module.exports = function(environment) {
  let ENV = {
    modulePrefix: 'nodal',
    environment,
    rootURL: '/',
    locationType: 'auto',
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. EMBER_NATIVE_DECORATOR_SUPPORT: true
      },
      EXTEND_PROTOTYPES: {
        // Prevent Ember Data from overriding Date.parse.
        Date: false
      }
    },

    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
    }
  };

  if (environment === 'development') {
    // ENV.APP.LOG_RESOLVER = true;
    // ENV.APP.LOG_ACTIVE_GENERATION = true;
    // ENV.APP.LOG_TRANSITIONS = true;
    // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
    // ENV.APP.LOG_VIEW_LOOKUPS = true;
  }

  if (environment === 'test') {
    // Testem prefers this...
    ENV.locationType = 'none';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';
    ENV.APP.autoboot = false;
  }

  if (environment === 'production') {
    // here you can enable a production-specific feature
  }

  return ENV;
};
```
`/mirage/config.js`
```javascript
export default function() {
  this.get('/routines');
}
```
`/app/routes/scenarios/index.js`
```javascript
import Route from '@ember/routing/route';

export default Route.extend({
  async model() {
    return await this.store.findAll('routine');
  },
});
```
`/app/adapters/application.js`
```javascript
import Route from '@ember/routing/route';

export default Route.extend({
  async model() {
    return await this.store.findAll('routine');
  },
});
```
`/app/models/routine.js`
```javascript
import DS from 'ember-data';

const {
  Model,
  attr,
} = DS;

export default Model.extend({
  condition: attr('string'),
  description: attr('string'),
  distinctInfoType: attr(/* object */),
  name: attr('string'),
  type: attr('string'),
});
```

`/mirage/models/routine.js`
```javascript
import { Model } from 'ember-cli-mirage';

export default Model.extend({
});
```

**Comment by mdbiscan** [comment]
I started a fresh app and installed mirage, worked perfectly. I'm not sure why this app is having issues, but its on my end. Thanks for your response, though.

**Comment by samselikoff** [comment]
No prob!

The 404 Ember Data error tells me Mirage _is_ responding, at least I think so... Do you see Mirage's response in the console? Try adding a .catch to your model hook?

Are you visiting `/routines/1` or something?

**Comment by mdbiscan** [comment]
The 404 error is not a mirage response, it's the adapter error from Ember telling me that `/routines` is not available. I've added the catch in the model hook, but it was redundant because the error in the catch was the same.

I'm visiting `/scenarios`, which is set up to have a `new` and `index` route, with the latter being the default for `/scenarios`. In that route file, I'm doing the store lookup for all routines, with `this.store.findAll('routine')`. Everything up to this point seems to be correct, the url is constructed and then reaches out with a `get` to `/routines`. But, its never intercepted by Mirage. I'm beginning to think this is a red herring, and there's an error somewhere else that isn't be exposed. I've tried deconstructing this to no avail. 

```Error while processing route: scenarios Ember Data Request GET /routines returned a 404
Payload (text/html; charset=utf-8)
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /routines</pre>
</body>
</html>
 AdapterError@http://localhost:4200/assets/vendor.js:71365:29
ErrorClass@http://localhost:4200/assets/vendor.js:71396:24
handleResponse@http://localhost:4200/assets/vendor.js:81182:18
ajaxError@http://localhost:4200/assets/vendor.js:81502:25
fetchErrorHandler@http://localhost:4200/assets/vendor.js:81547:12
ajax/<@http://localhost:4200/assets/vendor.js:81269:19
```

**Comment by samselikoff** [comment]
You tried a console.log in `mirage/config.js`, as well as in the mirage route handler? Simplify the route handler and try `console.log` at every step

**Comment by mdbiscan** [comment]
Yeah, I see that the mirage config is loading. I placed a debugger right before the `this.get('/routines')`.

**Comment by mdbiscan** [comment]
Interestingly enough, I replaced `this.store.findAll('routine')` with `fetch('/routines')` and that worked...

**Comment by mdbiscan** [comment]
I found out what the issue was:

`/config/options-features.json`
```javascript
{
  "jquery-integration": false
}
```
I set this to true, and now that jQuery is not entirely out of the picture, it works. I suppose I will need to remember to use the Fetch mixin next time ;). 

Thanks again for taking the time on this, @samselikoff.

**Comment by samselikoff** [comment]
I need to look into this bc I think others were having trouble with it. Sorry you ran into this!

**Comment by mdbiscan** [comment]
This may be related, but I'm trying to use the `association` helper, but my page doesn't render or display any errors whatsoever. I wonder if errors with mirage get swallowed up.

**Comment by samselikoff** [comment]
We were running into this - gotta get some failing tests over in miragejs/server. Think it has something to do with promises/async.

**Comment by zion** [comment]
I was having a similar issue, and found that every acceptance test that uses a route or ember data call, needs to have the `setupMirage(hooks)`. Otherwise every ember data call results in a 404.

**Comment by samselikoff** [comment]
Yes, Mirage used to autostart but now it needs to be started as documented in the [testing guides](https://www.ember-cli-mirage.com/docs/testing/acceptance-tests). I would just put it in a common helper so you don't have to write it in every file.

**Comment by samselikoff** [comment]
Closing this issue for now but if anyone's still having trouble please let me know!

**Comment by andreisebastianc-ccc** [comment]
I think I'm having trouble with this. I'm running acceptance tests and on some occasions, the route is not matched by Mirage. Unfortunately, it's not 100% reproducible. I'd say 33% of the time I have to refresh to get this issue and it seems to not be reproducing in development.

Here's what I'm getting:
![image](https://user-images.githubusercontent.com/30043915/72264371-51104f00-3623-11ea-8ba5-29bb955f48cf.png)

**Comment by samselikoff** [comment]
@andreisebastianc-ccc hmm, that's very bizarre... never heard of this before.

Yes, Mirage is indeed shut down & booted up on each test, so there's no state leakage between tests.

I wonder if one of the tests doesn't have `setupMirage`, or maybe its being called twice somewhere so some handlers are being overridden.

I would try to filter down the test suite until you can get a consistent reproduction. Start with the test by itself, gradually adding back more until you hopefully find some order-dependent issue or some test that's not cleaning itself up. That would be my first guess as to why you'd see some symptom like this.
