### ISSUE TITLE
Acceptance tests with ember exam and parallelization

### ISSUE THREAD

**Issue by teejayhh** [miragejs/ember-cli-mirage#1701]
This is just a quick question. We are seeing a few issues with ember exam and parallelization where tests fail with extra data being persisted in the mirage data base for some reason. Those tests are flaky and not happening all the time. 

An example would be that we have 3 records in db instead of the 2 which are created during the test. 

So I am wondering what has to happen for what we are seeing this behavior.

**Comment by samselikoff** [comment]
Hmm... typically mirage is reset on each test, so I'm guessing there's some leakage somewhere. There's no real shared state as mirage servers exist in the browser environment, so I think it might be somewhere in your tests?

Do your parallel tests run in the same browser?

**Comment by samselikoff** [comment]
If you can boil it down to a simplified reproduction I can definitely take a look!

**Comment by teejayhh** [comment]
Thanks for your answer, I / we will try to simplify the test suite. Maybe I forgot to mention that these flaky tests started when we enabled random test order. If we disable this feature then we are not seeing the problem. @timiyay might be having a few more information on this.

cheers Thomas

**Comment by samselikoff** [comment]
Closing for now but please let me know if you're still having trouble!
