### ISSUE TITLE
Add "Mirage logging" checkbox to QUnit user interface

### ISSUE THREAD

**Issue by Turbo87** [miragejs/ember-cli-mirage#1783]
<img width="302" alt="Bildschirmfoto 2019-10-09 um 14 43 31" src="https://user-images.githubusercontent.com/141300/66482704-cc51ea00-eaa3-11e9-96fb-30282cc5e92b.png">

QUnit has an API for adding checkboxes to it:

```js
QUnit.config.urlConfig.push({
  id: 'mirageLogging',
  label: 'Mirage logging',
});
```

The value of this checkbox is later available as:

```js
server.logging = QUnit.config.mirageLogging;
```

It would be great to have this be added by default when using `ember-cli-mirage` in combination with QUnit.

Happy to work on this if it is something that is considered useful :)

**Comment by samselikoff** [comment]
Sounds awesome – go for it!
