### ISSUE TITLE
Factories being ignored when generating data

### ISSUE THREAD

**Issue by Subaku** [miragejs/ember-cli-mirage#1834]
It appears as though mirage is not picking up and using my declared factories. When I start my dev server I can see the message `Mirage: [200] GET /api/v1/asset-location` and `Mirage: [200] GET /api/v1/place` in my console. When my app loads I also see the correct number of records in the Ember Data store for each. However, all their attributes are undefined. When I dig into the response data from those console messages there's also no attributes there either. I've also added `afterCreate(...)` functions to both factories with console logs just to see if they get called which they do not. 

Appreciate any help figuring out this weird behavior. 

Ember: 3.14.1
Ember-Data: 3.14.0
Ember-CLI-Mirage: 1.1.4

**Comment by Subaku** [comment]
Just to add that it does appear that my factories are being loaded but just not used. I suspect there's some camel-case issue happening? Here's a pic of the console output of the config that occurs inside server.js where `loadFactories()` gets called.
<img width="580" alt="image" src="https://user-images.githubusercontent.com/1900930/69688091-e9557300-1079-11ea-99a7-8ff614ac9a5a.png">

Hope this helps. Also I realized after the fact that this ticket maybe should have existed over in the miragejs repo. Sorry about that!

**Comment by Subaku** [comment]
Okay figured it out. When getting the attrs off a factory during the build phase it was getting back an empty dict. I was building my Factories using new ES6 Javascript classes instead of the `Factory.extend({})` syntax. Switching back made it work.

Feel free to close this issue if this shouldn't be labeled as anything.

**Comment by samselikoff** [comment]
Ya, sorry I know this is confusing as we're still on custom class syntax. It's actually not even Ember classes, it's our own thing. It's in our roadmap to figure out a more modern API.
