### ISSUE TITLE
Bump pretender dependency

### ISSUE THREAD

**Issue by mehulkar** [miragejs/ember-cli-mirage#1838]
Update pretender to 3.1.0 (or at least release lock from 3.0.x)

**Comment by mehulkar** [comment]
Specifically looking for this patch: https://github.com/pretenderjs/pretender/pull/280

**Comment by mehulkar** [comment]
A PR in miragejs already available: https://github.com/miragejs/miragejs/pull/227

**Comment by samselikoff** [comment]
https://github.com/miragejs/miragejs/pull/227 closes
