### ISSUE TITLE
Includes no longer supports spaces

### ISSUE THREAD

**Issue by YayFiber** [miragejs/ember-cli-mirage#1857]
# Bug 

👋 I'm in the process of upgrading my app from `~1.0.0` --> `~1.1.0` and found I could no longer write my includes in mirage queries like so: 

```js
await store.query('author', {
 include: 'genres, books.tags',
}) 
```

That results in an error reading: `Mirage: Error: You tried to include " books" with model:author(John Steinbeck) but no association named " books" is defined on the model.`

I instead need to change the include to `genres,books.tags`

I see that all `includes` are written this way in the mirage repository, so maybe this was always the intended behavior, nevertheless it introduced errors into our repo. 

You can see this in action in [this fiddle](https://ember-twiddle.com/c04d8bec96a956407880bb2edf709956?openFiles=routes.application.js%2C), although not the actual error message. I grabbed the error message from failing tests in my app. The `routes/application` file can be changed to show the difference in behavior.

Would love to help out if somebody doesn't mind pointing me in the right direction! 

Thanks,
Cam

**Comment by samselikoff** [comment]
I am surprised this changed - sorry you ran into it + it wasn't documented anywhere! However, I was never aware people were writing includes like this.

Looking at the spec I think this is one of the more strict parts: https://jsonapi.org/format/#fetching-includes. The examples all show comma-separated, with no space. 

We could make Mirage more robust here but I hesitate to account for out-of-spec edge cases. Seems like it might set you up for failure in the event your actual JSON:API backend doesn't support it.

I think you should change the includes to not use spaces, based on the spec doc & all the other implementations I've seen. What do you think – is it a huge blocker for you to update that code?

(Also, we could add some more helpful error messaging that verifies the validity of the includes string.)

**Comment by YayFiber** [comment]
Thanks for the response! I agree that Mirage should conform to the JSON:API spec in this case. 

It definitely is not a huge blocker in our code (it only existed in a couple of tests and was perhaps an oversight on our part), and I've already made the adjustment. Just wanted to bring it to your attention and perhaps help it be documented if necessary. Let me know if I can help in that respect.

**Comment by samselikoff** [comment]
Thanks for the issue 👍 I think the only action item would be to add some verification to the includes string in the JSONAPISerializer, if we wanted to make that improvement. If you feel up to it I would definitely accept that PR!

Since this is the first time someone's raised this issue, its lower priority for me. It's good we have this issue in case it happens again, and if it does, I would prioritize adding some stronger messaging around it.
