### ISSUE TITLE
Question: Does Mirage have the ability to lazily build out the mocked data?

### ISSUE THREAD

**Issue by NullVoxPopuli** [miragejs/ember-cli-mirage#1870]
Let's say you have 300+ models / with lots of different scenarios, traits, etc.

If you run one test that only _needs_ to access 3 of those models, is everything that wasn't accessed uninitialized / unloaded? 

My concern is about tests being slowed down due to populating Mirage's server's store.

**Comment by samselikoff** [comment]
Mirage's data layer has some speed issues right now. It's a priority to fix them but I'm focused on some other things at the moment.

In general I try to write tests that only create the data needed for that test. That should avoid most of the speed issues (unless your test absolutely demands 1000 models).

Do you have a specific test that's slow? 

(And to answer the original question, no you can't lazily build out data right now. Mirage's data creation logic is pretty basic.)

**Comment by NullVoxPopuli** [comment]
> Do you have a specific test that's slow?

I don't -- I'm actually doing some pre-pre-evaluation for adopting Mirage for CrowdStrike -- just kind of curious about some basic functionality.

> (unless your test absolutely demands 1000 models).

an individual test wouldn't, but it's possible than an entire test suite would eventually touch all the models, making up to 500 instances of each (not at the same time).

over the course of a test-suite's run, is memory managed in such a way that between tests factories+models are only loaded / used if invoked?

**Comment by samselikoff** [comment]
Yep, the default scenario is ignored and the Mirage + router config is loaded but no data is created. In that sense each test starts out with a clean db.

**Comment by NullVoxPopuli** [comment]
cool!

so, if I have a test that uses a model with a bunch of relationships, but I don't access any of those relationships - do those relationships get built?

**Comment by samselikoff** [comment]
They only get created when you call `server.create()`. So for example in [this guide](https://miragejs.com/docs/testing/application-tests#keeping-your-tests-focused), the second test will only have 1 record created in the db.

**Comment by samselikoff** [comment]
Let me know if you have any more questions!
