### ISSUE TITLE
Populate the included in json api relationship 

### ISSUE THREAD

**Issue by oliverlj** [miragejs/ember-cli-mirage#1882]
Question

Hello, i saw the question #1606 . I wonder if mirage could populate the included of a json api response with a has many relationship ?

**Comment by samselikoff** [comment]
Yes, it can using the [JSONAPISerializer](https://miragejs.com/api/classes/jsonapi-serializer) class.

Could you tell me how your client will be requesting the included data? (Do you want it to be a default server-side include, or are you requesting it using the `include` query params, e.g. `GET /posts/1?include=comments`)?

**Comment by oliverlj** [comment]
I have created an example repository : 

https://gitlab.com/oliverlj/ember-cli-mirage-1882

if I include this in config.js, this is working :

`this.get('/parents', (schema, /*request*/) => {
    // Working around #1
    // request.queryParams = request.queryParams || {};
    // if (!request.queryParams.include) {
    //   request.queryParams.include = 'children';
    // }
    return schema.parents.all();
  });
`

otherwise it not currently working

**Comment by samselikoff** [comment]
Just a naming mixup 🙈 

Your `parents` serializer needs to be singular: `serializers/parent.js`.

Also, in general you'll want to extend from your ApplicationSerializer. Right now your `parent` serializer is importing the root `Serializer` class from `ember-cli-mirage` and using that.

Instead try this:

```js
// mirage/serializers/parent.js
import ApplicationSerializer from "./application";

export default ApplicationSerializer.extend({
  include: ["children"]
});
```

**Comment by oliverlj** [comment]
This is doing the job, thanks
