### ISSUE TITLE
passThrough() not applied when fetching local files

### ISSUE THREAD

**Issue by andrew-paterson** [miragejs/ember-cli-mirage#1887]
When using `fetch` to get a local file, mirage throws a `no route defined to handle this request` even is `passThrough()` is used in `config.js`. 

The potential solutions suggested in [this Stackoverflow question](https://stackoverflow.com/questions/59944528/fetching-content-from-file-and-ember-cli-mirage/59952796?noredirect=1#comment106126100_59952796) didn't work.

I have reproduced the error [here](https://github.com/andrew-paterson/mirage-test). Unfortunately, Ember Twiddle didn't seem to work for fetching local files, so I had to create a new app to reproduce the error. The app simply fetches a markdown file and renders it in a component.

All of the potential solutions from the Stackoverflow question are commented out in `config.js`.

**Comment by samselikoff** [comment]
Sorry about the confusion!

`passthrough()` is such a weird API that we intend to improve in the near future. In the meantime...

The reason you're running into this is because `passthrough()` is being called after `urlPrefix` and `namespace` are being set, and so the passthrough call is taking those into account.

The solution is to either move the passthrough call to the top of the config file (before you set `namespace and urlPrefix`, or to reset the namespace/urlPrefix before calling passthrough again

```js
this.urlPrefix = ''
this.namespace = ''
this.passthrough() // this should work
```

**Comment by samselikoff** [comment]
Closing bc I tested on your repo and it seems to work, let me know if you run into anything else!

**Comment by andrew-paterson** [comment]
The above worked great! Is there any way to pass through all external requests?

For example, I know that I can use `this.passthrough('https://example.com')` to make Mirage ignore requests to `http://example.com` or `this.passthrough('https://example.com/**')` to make Mirage ignore requests to `http://example.com/foo` or `http://example.com/bar`.

With

```
this.urlPrefix = ''
this.namespace = ''
this.passthrough()
```

Mirage still intercepts the requests to external urls.

**Comment by samselikoff** [comment]
Right now if you use the normal form of passthrough you have to whitelist each external domain. But there's a function form you can try, something like:

```js
this.passthrough(request => {
  let isExternal = request.url.startsWith('http')

  return isExternal
});
```

**Comment by andrew-paterson** [comment]
Great! This code has worked for both use cases:

```
  this.urlPrefix = ''
  this.namespace = ''
  this.passthrough(request => {
    let isExternal = request.url.startsWith('http')
  
    return isExternal
  });
  this.passthrough()
```

So requests to both `/markdown/markdown-file.md` and `https://example.com` are being passed through. Thank you so much.

**Comment by samselikoff** [comment]
Awesome glad to hear!

We have an API coming to Mirage, `server.canHandle(requests)` which will return a Bool if Mirage has a route handler defined for a particular url. Once that lands I think we'll make 

```js
this.passthrough(request => !this.canHandle(request))
```

the default for passthrough which should address a lot of issues similar to this one!
