### ISSUE TITLE
Inflector initializer file name matters

### ISSUE THREAD

**Issue by yratanov** [miragejs/ember-cli-mirage#1911]
# Bug or question

`ember-cli-mirage` uses initializer to do some setup, but if custom inflector rules initializer is starting from any letter after `E`, it won't be counted. so I think docs should ask users to put `  before: 'ember-cli-mirage',` in their inflector initializer. In this case file name won't matter.

What do you think?

**Comment by samselikoff** [comment]
Hm - yes, I think that sounds correct.

I think [this guide](https://www.ember-cli-mirage.com/docs/advanced/customizing-the-inflector) should get the tweak, do you agree? Would appreciate a PR if you have the time!
