### ISSUE TITLE
Add primaryKey to the serializer just like ember data serializer 👍

### ISSUE THREAD

**Issue by cah-briangantzler** [miragejs/ember-cli-mirage#1942]
Extend the serializers to add the following code

```
// this is the name of the primary ID, if it is not present, use the attribute name
  primaryKey: undefined,

  keyForAttribute(attr) {
    if (attr === 'id') {
      return this.primaryKey || attr;
    }
    return attr;
  }
```

Many of my backend keys are not id, and in the ember data serializer I use primaryKey to rename them.    This would make the mirage serializers work very similar to the ember data counter parts

If this seems a reasonable request, let me know and I would be happy to do a PR

**Comment by samselikoff** [comment]
Yeah – probably reasonable, though is a pretty big change as this really belongs in the ORM layer rather than the Serializer layer.

We could do it in the serializer layer for now though – would you be ok if your mirage DB records all used `id`, as long as when they get seiralized over the network they get changed to your `pk` of choice?

In that case I think something like a new `keyForId` and `valueForId` hooks on the Serializer would solve both this problem as well as this SO question raised earlier today: https://stackoverflow.com/questions/61273522/convert-all-miragejs-ids-to-integers/61273523?noredirect=1#comment108401127_61273523

**Comment by cah-briangantzler** [comment]
I thought this went here because it would seem its only a problem when the models are generated for you (hence ember only). But if when you define a mirage model you also HAVE to use 'id', then yea.

And yea, perfectly fine with the the key being 'id' in the mirage database, dont expect you to mirror my backend database.

And `keyForId` was the first method I looked for.   

So I would suggest keyForId and valueForId in the mirageJs, and then in this repo extend the serializer with an overload of keyForId that implements the default primaryKey logic as a nice touch to to ember data serializer

**Comment by cah-briangantzler** [comment]
Now that im continuing on, it looks like I have the same problem for other fields i have renamed. I have the following on my serializer in ember data 

```
  attrs: {
    name: {key: "facilityName"},
    reorderPoint: {key: "flagReorderPoint"},
    lotAndExpirationView: {key: "flagLotAndExpirationView"},
    ndcSubItemsView: {key: "flagNdcSubItemsView"},
    network: {key: "networkId"},
    account: {deserialize: "records", serialize: "records"},
  },
```

which I think means I need to do a custom serializer and implement a keyForAttribute and a few others. Im am going to extend my application serializer to implement this using the same array from my ember data serializer but in reverse. This seems like something others would want as well and relates pretty closely to the primaryKey rename.

Seems this should also be some code implemented in this repo so people could just copy and past the serializer attrs.

Is this correct or am I missing something that should be obvious

**Comment by cah-briangantzler** [comment]
Hmmmm,    you already use serializer.attrs as a subset include :(

**Comment by cah-briangantzler** [comment]
This will be allowed for in this issue and prospective PR https://github.com/miragejs/ember-cli-mirage/issues/1989
