### ISSUE TITLE
Question: Where to set a static seed for Faker.js in ember application

### ISSUE THREAD

**Issue by vgrinko** [miragejs/ember-cli-mirage#1953]
Hi Mirage and Ember experts,

I need to make all tests in Ember application return the same results across runs.

All my tests are using faker.js to generate random data. I still want it to be generated, but want it to be the same (when I need it).
I found that Faker.js has [ability to set randomness seed](https://github.com/marak/Faker.js/#setting-a-randomness-seed), which is designed for this problem.

My question is where/how to set this seed, so results are consistent across all tests - considering ember/mirage architecture?

What I tried:
1. `tests/test-helper.js` - this does not work cinsistently, because I use `ember exam`, and tests run in different siquence, hence Factories are initialized in different order.
Based on this I realized that seed need to be set on the level of each test
2. override `ember-cli-mirage/test-support/setup-mirage`
This works mostly, but I found that while it works for factories themselves, it does not work for traits which use faker - I see that traits are executed *before* `setup-mirage` is executed.
Example of trait for which it does not work:
```
  withMySpecialCase: trait({
    randomField: faker.random.number();
  }),
```

Much appreciate any help or advice.

**Comment by samselikoff** [comment]
When I've done this I do it right at the top of `mirage/config.js`:

```js
import faker from 'faker';

faker.seed(123)

export default function() {
  this.get('/posts', ...
}
```

**Comment by vgrinko** [comment]
Thank you @samselikoff for this suggestion!
Am I correct that `config.js` is executed for every single test? Previously i assumed it's only ran once.

Your solution is way better than #2 solution I tried, because it solves config.js overrides + tests themselves.

but it still does not solve the problem of traits which use faker.

after further digging, I found that if instead of 
```
withMySpecialCase: trait({
    randomField: faker.random.number();
  }),
```

I wrap a field which is using faker 

`withMySpecialCase: trait({
    randomField() { return faker.random.number(); }
  }),`

then trait starts respecting seed set either in `setup-mirage` or or in `config.js`

Do you know why and if that's a right approach?

**Comment by samselikoff** [comment]
Yeah – you should never do

```
{
  randomField: faker.random.number()
}
```

because that will run once, at eval-time, instead of every time a model is created, at runtime.

```
Factory.extends({
  someProp: 4,
  anotherProp: 1 + 3,
  aThirdProp: function() {
    return 1 + 3
  }
})
```

See how the value for `someProp` and `anotherProp` are "evaluated" when the Factory is loaded? Whereas the value for `aThirdProp` is a function that isn't evaluated until Mirage calls on it? That's more or less what's going on here 👍

**Comment by vgrinko** [comment]
Understood - makes sense.
Thank you very much for detailed response!

**Comment by samselikoff** [comment]
You're welcome!

**Comment by sebastianhelbig** [comment]
The proposed solution `faker.seed(123)` in at the top of `mirage/config.js` does not seem to work anymore. I am always getting the same random data :-( Anyone has an idea?
