### ISSUE TITLE
Handle both implicit and explicit `include` for a single request

### ISSUE THREAD

**Issue by jordpo** [miragejs/ember-cli-mirage#2003]
Hi, 

Not sure if this is a feature request or a bug. Should be easy to replicate. We have a resource that we specify `?include=` when we make a request. The associated records that are included also have relationships that we want to side load. We specify the `include: Array<string>` in the serializer however the `queryParam.include` overrides the settings there. 

For example

GET `/posts?include=comments`

`CommentSerializer. include = ['user']`

The expectation is that the payload for the request returns both all `comments` related to posts and the associated `users`. Currently it will just return `comments` and not `users`. 

As far as I understand, the JSONAPI spec does not disallow the combination like the above of both an implicit and explicit include. Especially as the `queryParams.include` relates to just the top level resource requested and not the associated resources, and therefore there is no explicit way of adding an `include` for them. 

Like I said, not sure if this is a feature or a bug. We've run into this issue a few times in our production app. The work around that I have in place is to manually remove the `queryParams.include` in a custom `serialize` function override in the Serializer class. This then allows for the default behavior for an implicit include for all associated resources. 

```
 PostSerializer extend BaseSerializer {
  include: ['comments'],

  serialize(object, request) {
    // NOTE Mirage doesn't handle both query param include and an implicit include for associated records
    delete request.queryParams.include;

    return BaseSerializer.prototype.serialize.apply(this, arguments);
  },
}
```

Thanks!

**Comment by samselikoff** [comment]
(Hey Jordan!)

I do think the JSON:API spec does say, if the request has an include query param that it must take precedence over any default server-side includes. And this is how Mirage behaves today.

Fortunately JSON:API also has a way to support what you're asking: dot-path includes. You just need to include all nested relationships using dot notation. Here's a REPL:

https://miragejs.com/repl/v1/152

Try loading that, then making a GET request to `/posts?include=comments.user`. You should see each comment's user included in the payload.

Let me know if that helps!

**Comment by jordpo** [comment]
Hey Sam!

Thanks for the information! Here is the section you were referencing from the spec - https://jsonapi.org/format/#fetching-includes.

Makes sense and glad to hear about the dot notation for nested relationships with `include`. Going to close this issue.

Thanks again!
