### ISSUE TITLE
v1.1.7 breaks node 8

### ISSUE THREAD

**Issue by kellyselden** [miragejs/ember-cli-mirage#2020]
v1.1.7 includes updates to broccoli-funnel and broccoli-merge-trees which drop node 8. The engines field of ember-cli-mirage still indicates support for "6.* || 8.* || >= 10.*".

**Comment by samselikoff** [comment]
Sorry about that 😕

What should we do - downgrade those deps or just publish a major version release?

**Comment by kellyselden** [comment]
I think you should merge #2025 and release it as v1.1.8. Then it would be up to you whether to release a major with those rebumped, or delay a major.

**Comment by kellyselden** [comment]
And here's a PR to start off a new major if you want it https://github.com/miragejs/ember-cli-mirage/pull/2026.
