### ISSUE TITLE
Allow Mirage to use primaryKey and attrs from ED Serializers.

### ISSUE THREAD

**Issue by cah-briangantzler** [miragejs/ember-cli-mirage#2037]
For people not using JSON-API in their server, this applies to using the REST Serializer of Ember Data.

When using the `primaryKey` or the `attrs` key properties to rename fields of the Ember Data Serializer, this code has to be reproduced in the mirage serialize and normalize function. You could in Mirage use the new names, but this would leave my mirage model with different property names than my server and since mirage is suppose to mimic the server, I like things clean.

Within the `attrs`, if you are using the embedded records mixin, you have the ability to specify IDs, records, or serialize false.

Allow mirage to utilize this information and auto-create or extend the mirage serializer much like to does for creating mirage model relationships from Ember Data Models.

Proposed Solution.

Create an `EmberDataSerializier` based off the current Rest Serializer that will do the following:

1. contain a `primaryKey` property: This will be the name used in normalize/serialize instead of `id`.

2. contain a hash named `transform` (mirage already used `attrs`) that will look exactly like the ED serializers `attrs` property. Mirage will then use this transform for property name renames and embedding records or IDS.  This will replace the current properties `embed` and `alwaysSerializieIds` (which pertained to every relationship in the serializer and now would be property by property).  If a relationship exists and there is no entry in the `transform`, it will assume serialize by id the same as the ember data serializer does now.

3. Modify mirage to populate these properties from the Ember Data Serializers so we would not have to code them on the mirage serializer definitions.

I found that almost all my custom serializer code I had to write would be replaced by this. I hope this would also reduce the mirage serializer code others are writing as well.

**Comment by cah-briangantzler** [comment]
Anything I can do to help get some movement on this?

**Comment by cah-briangantzler** [comment]
Do you know when a release of master, containing the ability to configure the mirage server might be released? Would this possible me included? Or you want to release master first, then this possibly in the next release.

Im really thinking for the end user, this feature being within ember-cli-mirage is the correct thing to do. But given your time being able to be devoted to ember-cli-mirage, it might be better as its own addon. To do a separate addon though, it is dependent on whats in master being released.

**Comment by samselikoff** [comment]
I think it can be in ec-mirage.

Something that would help move this forward would be to break things down a bit more. When I go through issues and check up on this, there's always a lot of information to process, and it takes me too long to remember where we left off so it's easier to focus on other things.

If you could help keep things focused on one small next step at a time, that would help move things forward. For example in your latest comment

> Do you know when a release of master, containing the ability to configure the mirage server might be released? Would this possible me included?

I don't know what the last part of this means. It would be more helpful if you just had a small issue or comment that said something like "Next step is to cut a release of master so I can start using `makeServer`. Let me know if there's anything I can do to help move that forward."

I just wanted to take the time to write this because part of what's making this take long is the communication.

That being said, is a new release of master the next step?

**Comment by cah-briangantzler** [comment]
The PR has been posted with no comments for almost a month, my follow up comments were attempting to give you choices and it appears to have complicated it. Sorry. 

I have posted a PR #2038 the that does the following: 

- Updated the dummy/mirage/config to use the new makeServer
- Removed test project 3 - no longer needed to test new config as dummy app/tests is now doing that. Original still supported config is being tested with Test Project 1
- Added a serializer EmberDataSerializer for use. Included tests.
- Added two methods to ember-data.js to support the discovery of ember-data serializers similar to ember-data models.
- exposed the new serializer on ember-cli-mirage
- exposed the serializer discovery on ember-cli-mirage

This is all additional code for opt in use and does not alter the current functions of ember-cli-mirage.

I believe the next step is to review and merge this PR.

**Comment by samselikoff** [comment]
Added you to ec-mirage, feel free to not let me block you! And if you want my input let's try using reviews and I'll try to stay on top of them 👍
