### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by chrismllr** [miragejs/ember-cli-mirage#2082]
Any chance for a release soon? I've got this addon-guard notification, and noticed the `ember-get-config` dependency version is updated to `0.3.0` on the master branch.

```
ember-get-config
----------------------------------------
my-app
├─┬ ember-cli-mirage
│ └── ember-get-config@0.2.4 (cacheKey: b37f276e40fd793ce66813dfb160f912, runtime: true)
├─┬ ember-cli-moment-shim
│ └── ember-get-config@0.3.0 (cacheKey: ffb52ed19a11426f4028bc2838e5cf87, runtime: true)
└─┬ ember-power-calendar-moment
  └─┬ ember-cli-moment-shim
    └── ember-get-config@0.3.0 (cacheKey: ffb52ed19a11426f4028bc2838e5cf87, runtime: true)
```

**Comment by samselikoff** [comment]
There's been some issues with the dev build that has been blocking a release: https://github.com/miragejs/ember-cli-mirage/pull/2081#issuecomment-735860430

If you are motivated + have time to help out, that would probably be the fastest way to get to the release! I'm personally focused on other things at the moment so can't help out on this.

**Comment by cah-briangantzler** [comment]
These above mentioned issues have been taken care of

- the docs not working on ember-cli-mirage for master branch) 
- acceptance tests not working with ember try because addon docs only supports 3+

I think we are clear to make a release.  While I dont recall anything that was specifically a breaking change, I believe Sam wanted to bump the major version number if I recall

**Comment by samselikoff** [comment]
https://github.com/miragejs/ember-cli-mirage/pull/2025 Think we reverted this so we need to make sure we hvaen't changed anything since. That's what the major was for.

**Comment by samselikoff** [comment]
Looks like we dropped node 6 and 8 in our package.json so we do need to bump.

I'll defer to @Turbo87 here.

https://github.com/miragejs/ember-cli-mirage/compare/v1.1.8...master#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L98

**Comment by Turbo87** [comment]
yep, seems reasonable :)

**Comment by samselikoff** [comment]
Ok yep I'd say go ahead and release and just bump to 2.0 and note why!

**Comment by Turbo87** [comment]
if you're talking to me, I don't have npm permissions 😅

**Comment by samselikoff** [comment]
Haha meant @cah-briangantzler because he's been kinda driving this from something he needed, but happy to add you to npm if you'd like (with no expectation of doing any maintenance work!)

**Comment by samselikoff** [comment]
This is you correct? https://www.npmjs.com/~turbo87

**Comment by samselikoff** [comment]
Figured we haven't gotten to the point of people impersonating npm users but never hurts to ask 😁

**Comment by Turbo87** [comment]
yeah, as far as I know that should be me :D

**Comment by samselikoff** [comment]
gotcha :) Added!

**Comment by Turbo87** [comment]
v2.0.0 is running through TravisCI now and will hopefully be available on npm soon. 

turns out I probably didn't need the npm access if CI is doing the release for me 😅

**Comment by samselikoff** [comment]
Oh yeah - derr. That's one of the reasons I did that, so I didn't have to add people to npm 🙈 Oh well!

**Comment by Turbo87** [comment]
alright, v2.0.0 is up on npm now. closing this issue :)

**Comment by cah-briangantzler** [comment]
Thanks for doing this. Was a little nervous to do it, first time. 

I updated my app to 2.0.0 no problem.

Can not yet confirm upgrading to qunit 5 as https://github.com/san650/ember-cli-page-object needs an update as well
