### ISSUE TITLE
Mirage logging checkbox doesn't render in ember-qunit v5 

### ISSUE THREAD

**Issue by ijlee2** [miragejs/ember-cli-mirage#2091]
## Description

After upgrading an app to `ember-qunit v5`, I noticed that the Mirage logging checkbox (shown in the screenshow below) was no longer rendered.

<img width="1187" alt="mirage_logging" src="https://user-images.githubusercontent.com/16869656/101406344-f1f0a400-389e-11eb-81cd-813f1c41ea99.png">

I am still able to get Mirage server logs by manually adding the query parameter `mirageLogging` to the test URL.

I created a [minimal reproduction](https://github.com/ijlee2/mirage-logging-with-ember-qunit-v5).

1. Switch branch to either `main` or `upgrade-ember-qunit-to-v5`.
1. Run `yarn install` to install `ember-qunit v4.3` or `v5.1`.
1. Run `ember t -s` to check if Mirage logging checkbox appears

## References

- [Pull request that had added Mirage logging in `ember-qunit v4`](https://github.com/miragejs/ember-cli-mirage/pull/1818)
- [`ember-qunit v5` migration guide](https://github.com/emberjs/ember-qunit/blob/master/docs/migration.md)
- [`qunit-dom` migration guide](https://github.com/simplabs/qunit-dom#ember-projects-using-ember-qunit-v5x-and-above)

**Comment by cah-briangantzler** [comment]
The code that is adding the checkbox is using the Global Qunit which Qunit V5 is no longer exposing. We have to conditionally import Qunit

Fixing a dependency of one add on to another in a backward compatible way could be challenging.

Working on it.

**Comment by cah-briangantzler** [comment]
Adding the following lines to test-helper.js will also work

```javascript
import QUnit from 'qunit';

QUnit.config.urlConfig.push({ id: 'mirageLogging', label: 'Mirage logging', });
```

Still determining if ember-cli-mirage should be doing this for you or not.

**Comment by ijlee2** [comment]
@cah-briangantzler Thank you for working on this!
