### ISSUE TITLE
Who is maintaining this addon?

### ISSUE THREAD

**Issue by cah-briangantzler** [miragejs/ember-cli-mirage#2240]
This addon is no longer being maintained by the owner. Recently ember-addopted-addons was given the ability to maintain this addon.

@MelSumner 
    

- Is this addon going to be moved to ember-adopted-addons or stay in the miragejs org?
- Who in adopted addons is going to be maintaining and releasing this?
- There are several PRs that need to get completed due to deprecations.
- I am going to cancel all my pending PRs and start over making a few targeted ones to ease the deprecations. Is there someone that can approve these. I have no problem attempting to maintain this, just not very proficient in releasing an addon. Seeing as this is pretty visible, would not like it to be my first :)
- There will be a PR that will be a breaking change. We need to remove all the re-exports to make this just responsible for the things it adds. I have not found a way to deprecate the re-exports though, any ideas? At this time I would also suggest removing the old way of creating a server and use just the new way. This new way more closely resembles the documentation in MirageJs proper.

**Comment by cah-briangantzler** [comment]
There is a release video in issue https://github.com/miragejs/ember-cli-mirage/issues/2055 I will re-watch this and see if I cant get a release out containing just a couple PRs for my first attempt.

**Comment by cah-briangantzler** [comment]
I was unable to do a release. While I have sufficient permissions for this repo, I lack the permissions to push to NPM.

**Comment by cah-briangantzler** [comment]
It looks like I and @SergeAstapov are at the moment.

**Comment by rahulk94** [comment]
👏🏾  awesome to see traction being made here again @cah-briangantzler and @SergeAstapov
