### ISSUE TITLE
Community feedback: Keep this addon on create a new one

### ISSUE THREAD

**Issue by cah-briangantzler** [miragejs/ember-cli-mirage#2243]
Since this addon is no longer being maintained, it is in the process of being moved to ember-adopted-addons (permissions and such still being worked through). I have wanted to try and keep the name as it is familiar with the community.

Should we try to keep this addon and name alive? Or would the community be ok with replacing this addon with a new addon with a new maintainer. 

A new addon would work as this one does with a few minor breaking changes that can be fixed with a search and replace. This will allow for a lot of the cruft to be stripped.

**Comment by kpfefferle** [comment]
`ember-cli-mirage` has a TON of familiarity within the ember ecosystem. Assuming that we'd continue to rely on `miragejs` under the hood, the current name also follows standard ember-addon naming conventions. I would think we'd need an extremely compelling reason to change the name 🤔

**Comment by cah-briangantzler** [comment]
> the current name also follows standard ember-addon naming conventions

In the beginning every addon had the `cli` in the name. Later it was adopted to only include the `cli` in addons that altered the build pipeline like `ember-cli-deploy`, if it did not, drop the `cli` like `ember-qunit`. I would think this addon acts more like `ember-qunit` and is actually not named for the current standard. 

Have definitely been trying to keep the name, but thats why issues have been unresolved for months. Since Sam is no longer maintaining this, getting permissions to the repo, npm, etc has been the stalling point. Some permissions have been given to ember-adopted-addons.

The only reason I suggested going with an other repo was to finally get the ability to make some forward progress. The suggested  name would be `ember-mirage` (`ember-miragejs`?) which is more the current standard as stated above. I have actually done all the work and its just sitting there waiting because I do agree, I would like to keep the name.

**Comment by SergeAstapov** [comment]
@cah-briangantzler tbh I'm not sure a new addon makes sense as in that case migration may be rough.

Instead, I suggest releasing v3 with deprecation for all the things we'd like to drop from this addon, dropping old Node.js versions, etc.

v4 would remove all the deprecated features.
That way, all users of the addon can have a smooth path by doing:
1. Upgrade to v3
2. get rid of any deprecations
3. upgrade to v4

I think biggest problem for some time was that Sam moved on and e-c-mirage was sort of abandoned.

IMO it would more helpful long term to keep existing addon and evolve it as we can have more traction / attention / maintainers.

I really like how Ember Community approach common problems and puts effort toward single shared solution rather than spread effort across multiple projects.
Ember Community is not that big so having two projects for the same purpose may cause distraction.

The only reason I think it makes sense to create another addon if the new one would have a different philosophy where two approaches can't coexist in single project for architectural or other reasons.

**Comment by cah-briangantzler** [comment]
I totally agree and have been attempting that for months. One of the things that need deprecated is that re-export of all miragejs. I spent some time and could not figure out how to deprecate that. So theres one deprecation that might not be able to be done.

The Docs need stripped down a lot, to do that you are also going to need to update ember-cli-addon docs, a lot of work.

The migration path isnt rough. I did my app at work in 5 min and all the tests run.

I have full admin rights to the repo so cant fix that all there. But still do not have rights to publish to NPM. 

If your curious, since I had to do the work anyway, the new repo is https://github.com/bgantzler/ember-mirage with the docs at https://bgantzler.github.io/ember-mirage/ (some copy paste from the ember-cli-mirage docs so I might have missed a typo or two) with the migration doc at https://bgantzler.github.io/ember-mirage/migration/

If you take a test branch, I bet you could update your app in a couple minutes. 

Im not saying use the new addon, but I also currently cant publish ember-cli-mirage either.

**Comment by rtablada** [comment]
I like the move to modernize, but agree that the addon name should be kept where possible. The adopted-ember-addons have a lot of experience with working with older maintainers to get a trusted NPM authorship and stuff.

**Comment by kitsuneyo** [comment]
Just speaking as a consumer, I really don't mind whether it's a new name or not and think you should go with whichever has the smoothest path. Appreciate the work going into this.

**Comment by cah-briangantzler** [comment]
We have published a new release, so ember-cli-mirage is the name we are attempting to stick with.

**Comment by jrjohnson** [comment]
Just seeing this discussion. @cah-briangantzler I'm 100% behind whatever you want to do here to move forward. If we need to make some changes, update old guides, etc in our app we'll do it. It looks like keeping the name for now, but if you want to do a hard breaking change at v3 without taking a bunch of time to add in deprecations all over or remove everything and get a fresh start or move to a new name that's no problem. Being able to use mirage in our tests is absolutely critical to our app and anything that keeps this API alive and continues to keep up with changes to idiomatic ember and build systems is a very welcome.

**Comment by cah-briangantzler** [comment]
The deprecation work has already been done with an great thanks to @SergeAstapov

**Comment by kpfefferle** [comment]
@cah-briangantzler If the decision is to stick with `ember-cli-mirage` for now since you've gained deploy access, can this issue be closed?

**Comment by cah-briangantzler** [comment]
I left if it open in case someone wanted to respond but yea, this can be closed
