### ISSUE TITLE
FYI: faker.js is no more

### ISSUE THREAD

**Issue by MelSumner** [miragejs/ember-cli-mirage#2298]
Just a heads up that faker.js is no more- the most recently published version is empty. There are forks available; also chance.js has been pegged as a potential replacement.

**Comment by mattandersonfg** [comment]
There's also a new "official, stable fork of Faker" at https://github.com/faker-js/faker

**Comment by cah-briangantzler** [comment]
Faker is actually listed as a devDependancy so it would only be used in the Docs / demo app. However searching the code I dont actually see if imported anywhere.

We should look into removing it from the devDependancies

**Comment by SergeAstapov** [comment]
@cah-briangantzler I think guides is where we use faker and that may need an update

**Comment by cah-briangantzler** [comment]
Yes the guides give an example of using faker in snippets, not actual running code, so we can remove the devDependancy on faker now.

That part of the guides that actually should be removed though :) MirageJS is where that functionality now lies and should be documented there. This repo is only meant for integrating MirageJS into Ember, not explaining how MirageJS works.

Once we trim down the docs and only document what this addon is actually doing, that will all go away.

I checked MirageJS docs and they mention faker here https://miragejs.com/docs/main-concepts/factories/ But it should really be up to them to update their docs how they wish.

**Comment by SergeAstapov** [comment]
https://github.com/faker-js/faker seem to be legit successor

**Comment by ijlee2** [comment]
I can also recommend using [`@faker-js/faker`](https://github.com/faker-js/faker).

While making a demo app, I realized that this library allows the same API calls (at least, for the methods that I needed). So all I'd need to change is the import statement.

```ts
/* Before */
import faker from 'faker';

/* After */
import { faker } from '@faker-js/faker';
```

This week, I was able to quickly replace `Marak/faker` in a production project.
