### ISSUE TITLE
Mirage not intercepting requests

### ISSUE THREAD

**Issue by viganella** [miragejs/ember-cli-mirage#2429]
After updating project to latest Ember LTS (3.28 .5) mirage is not intercepting the calls. 
**Ember data was updated also from 3.24 to 3.28 which seems to affect this.**
The request is identified when checking the network in browser with obvious result of 404.
I have ember-cli mirage version 2.4.0. I have also ember-fetch installed, version: 8.1.1.
Happy to provide more info if needed. 
In the config.js, I got:
`  this.post('/cloudTags', (db, request) => {
    let tag = JSON.parse(request.requestBody).cloudTag;
    tag.fingerprint = 'asdas-dasdas-asdasd-asdasd';
    return db.cloudTags.create(tag);
  });`

![sample](https://user-images.githubusercontent.com/2545516/179512790-02e96cb1-6790-4f4b-9508-3cf7d723d49a.png)
![sample1](https://user-images.githubusercontent.com/2545516/179512957-3f475959-852f-43ad-8df1-f9fe735d5535.png)

**Comment by mileszim** [comment]
@viganella what did you find? I'm having a similar issue
