### ISSUE TITLE
v3 upgrade guide? 

### ISSUE THREAD

**Issue by mansona** [miragejs/ember-cli-mirage#2453]
# Feature request

I noticed that there is a lot of work happening with the V3 push but I am wondering what work has been done in terms of an "Upgrade Guide" for people to move from the old system to the new hotness? 🤔 

If nothing has been started I could make a stab at it, but I would appreciate some guidance on where to start 👍

**Comment by SergeAstapov** [comment]
@mansona there is a stub about deprecations added in v2 https://github.com/miragejs/ember-cli-mirage/blob/master/packages/ember-cli-mirage-docs/app/templates/docs/getting-started/upgrade-guide/v2-deprecations.md

In terms of what to highlight to this point, probably PRs #2314 and #2341
