### ISSUE TITLE
Mirage cannot preload assets

### ISSUE THREAD

**Issue by abeaudoin2013** [miragejs/ember-cli-mirage#2488]
When I run tests that try to fetch assets, a Mirage error surfaces in my console:

<img width="1072" alt="Screen Shot 2023-02-08 at 10 13 31 AM" src="https://user-images.githubusercontent.com/13140773/217618252-5c2fc639-48ab-4e67-90e2-48fc89e5caa8.png">

Essentially it's complaining that the route to this asset is not defined in the mirage config file's routes() function. This particular error comes from a request to a CDN, however I get this same complaint when trying to fetch assets that live within my project directory. 

When I add these routes using `this.passthrough('https://cdnjs.cloudflare.com/ajax/libs/**')` for example, I get a timeout error that looks like this: 
<img width="562" alt="Screen Shot 2023-02-08 at 10 43 50 AM" src="https://user-images.githubusercontent.com/13140773/217622960-d84e21a6-28eb-438b-806c-d0e38eb6bb47.png">

It becomes further complicated when I isolate a particular module throwing this error because then I do not see the error at all. It only occurs when I run the whole test suite.

Any idea what I could be doing wrong?

**Comment by cah-brian-gantzler** [comment]
ember-cli-mirage is a thin wrapper to import mirageJS. Someone better may know if you place this on https://github.com/miragejs/miragejs. Since this also has to do with passthru, based on some of the other issues it might be better on https://github.com/pretenderjs/pretender since thats what mirage uses to do the actual interception

**Comment by abeaudoin2013** [comment]
Thanks, Brian. I kind of figured I might have to post there, but thought I'd try here first. I'll take a look.
