### ISSUE TITLE
discoverEmberDataModels() fails if any pre Octane style Ember model has a property named `errors`

### ISSUE THREAD

**Issue by andrew-paterson** [miragejs/ember-cli-mirage#2497]
Using Ember data 3.28.0 and Ember CLI Mirage 2.4.0.

If your model is defined in the non class-based syntax, and it has a property names `errros`,  then this line `models: { ...discoverEmberDataModels(), ...config.models },`  in `mirage/config.js` throws an error because the `discoverEmberDataModels` function throws an error.

Updating the model in question to the class-based syntax resolves the issue.

**Comment by SergeAstapov** [comment]
@andrew-paterson given the whole ecosystem moves to "just use the platform", native classes have been available for a long time and as you described using there is a super simple way to fix this, I don't think we should do anything in this addon.
